### ISSUE TITLE
Integrate with React-Window caused incorrect focused element

### ISSUE THREAD

**Issue by hantrungkien** [NoriginMedia/Norigin-Spatial-Navigation#35] opened 2022-09-27 06:10 UTC
**Describe the bug**
Based on your example, I've created a demo with react-window. But when key-up and key-down are pressed, focusable element is wrong.

**To Reproduce**
https://codesandbox.io/s/happy-voice-8hmrt0

```
yarn start
```

And then press key-down you can see focus move from row 1 -> row 2 -> row 4.

And then press key-up you can see focus move from row 4 -> row 3 -> row 1.

**Screenshots**

https://user-images.githubusercontent.com/20286370/192446409-5d7b47d6-a815-4eb9-91ac-d99ed4d30b44.mp4

**Comment by guilleccc** [comment] 2022-12-13 13:58
Hello @hantrungkien ,

I looked at your example, and after adding the `init()` I could see what you were reporting above.
At your example, you defined the following code:
```
<FixedSizeList
          layout="horizontal"
          direction="ltr"
          innerRef={ref}
          outerRef={scrollingRef}
          height={window.innerHeight / 3.5}
```

I think `height={window.innerHeight / 3.5}` is causing some issues on navigation due to having a float value. I don't know exactly why you would use this sort of values, but to me is an edge case. I believe the float number makes collapsing between some "boxes", and that produces an incorrect navigation.
As a quick solution you can use `parseInt(window.innerHeight / 3.5)`, as you will find in [this example](https://codesandbox.io/s/elegant-sinoussi-jwqr5r?file=/src/App.tsx) as well.

Alternatively you can use a fixed value (e.g.: height=200).


This combination of react-window with float number is quite uncommon, so I will close this issue for now. Feel free to reopen if you reproduce this issue in other scenarios

**Closed by guilleccc** 2022-12-13 13:58 UTC
Labels: bug, question
