### ISSUE TITLE
Focus is not Working properly when Stack navigation is Added

### ISSUE THREAD

**Issue by GitHubShasiKumar** [NoriginMedia/Norigin-Spatial-Navigation#106] opened 2023-11-14 08:20 UTC
https://github.com/NoriginMedia/Norigin-Spatial-Navigation/assets/107665648/3021ba88-2968-4c2e-a65e-830e94ee2ec8

Hi @asgvard 

The focus is missing or disappering when navigating to next screen,
I enabled the visual debug in init ,
when Iam navigating to next screen in Stack , i dont understand where the focus is going and i am getting the previous screen layout,

iam using.  react native web for webos and tizen tv
 "@noriginmedia/norigin-spatial-navigation": "^1.3.1",
        "@react-navigation/native": "^6.1.7",
        "@react-navigation/stack": "^6.3.17",
        "react-native-web": "^0.19.6",
        "react": "18.2.0",
        "react-dom": "^18.2.0",
        "react-native": "0.72.3",

Please help me out
thank you

**Comment by predikament** [comment] 2023-11-16 16:36
Closing this as duplicate of #107..

**Closed by predikament** 2023-11-16 16:36 UTC
