### ISSUE TITLE
focusSelf causes everything to be focused on Chrome

### ISSUE THREAD

**Issue by tieugioh** [NoriginMedia/Norigin-Spatial-Navigation#8] opened 2022-04-25 22:45 UTC
**Describe the bug**
Calling focusSelf() causes all focusable components to be in focusable state until arrow buttons are pressed

**To Reproduce**
see this example:
https://codesandbox.io/s/spatial-nav-example-66wiu9

**Expected behavior**
First focusable child should be in focused state only.

**Comment by asgvard** [comment] 2022-04-29 18:07
Hi!

This is very interesting...
I have tried your example, and it works fine when I remove StrictMode in `index.js`. Apparently it has something to do with this. I will need to have a look.
When looking at our example in `App.tsx`, we have very similar case:
https://github.com/NoriginMedia/Norigin-Spatial-Navigation/blob/main/src/App.tsx#L167
But there is no such issue.
It seems like all your `Items` are getting completely re-mounted, and their `focusKeys` are getting generated over and over, causing multiple items to have the same key. Focus key generation is happening here:
https://github.com/NoriginMedia/Norigin-Spatial-Navigation/blob/main/src/useFocusable.ts#L115
And it is memorized, so as long as the item remains mounted, its `focusKey` is persistent, even if it was automatically generated.

But it's definitely interesting, worth investigating :)

**Comment by asgvard** [comment] 2022-04-29 18:16
I have tried Strict mode in our App example and it works fine, however I've found that it doesn't work when I use:
```
import { createRoot } from 'react-dom/client';
```
When using good old `ReactDOM.render(<App />, document.querySelector('#root'));` - it works fine.

So the problem is somewhere in this `createRoot`. It seems like it causes all the items to be remounted on every render cycle.

**Comment by asgvard** [comment] 2022-04-29 19:00
Something is weird with this new `createRoot` + `StrictMode`. It is only reproducable with this combination.
Works fine with the old `ReactDOM.render`, and works fine without `StrictMode`.

I've made even simpler example here: https://codesandbox.io/s/spatial-nav-example-bk72gs?file=/src/App.js
As you can see, the `App` is mounted twice, and every state update increments the counter by 2. I would monitor React repo itself and see for similar issues, and if nothing, open a new issue there.

**Comment by tieugioh** [comment] 2022-05-02 20:36
Thanks for looking into this! i had a hunch it had something to do with react 18...  I did a quick search in the react repo for this issue and didn't see anything related yet. In the meantime I'll probably stick with `ReactDOM.render`.

**Comment by tieugioh** [comment] 2022-05-02 21:59
https://reactjs.org/blog/2022/03/29/react-v18.html#new-strict-mode-behaviors this might have something to do with it.

**Comment by asgvard** [comment] 2022-06-01 11:17
I think the problem mostly lies in this new "createRoot", so unless you need some specific features from it, I would skip it for now. However if you don't need any specific features from StrictMode, you can of course omit it as well.
We will look more into the root cause for this and how to make it work with both.

**Comment by asgvard** [comment] 2022-06-07 13:52
Thanks! Nice find, I will watch it and see if it helps. Ohh, time to dive deeper in React v18 😃

**Comment by babysteps** [comment] 2022-08-29 17:30
i am also running into this issue related to React 18.  i have found that running strict mode in dev everything works, however once i generate a build (which does not use strict mode) that the spatial navigation does not work properly.  any word on when this update might be made to the lib?

**Comment by asgvard** [comment] 2022-09-08 10:37
Hello! This issue should be now fixed in v1.1.0 🎉 We are using new `useEffectOnce` hook to avoid the "double mount" that is coming from the React v18 StrictMode.

**Closed by asgvard** 2022-09-08 10:37 UTC
Labels: help wanted
